#!/bin/bash

jarfile=my-jarfile.jar
maxmem=1024m
JAVAOPTS=
JAVAARGS=

# encoding might be broken otherwise
export LANG=en_US.UTF-8

exec java -XX:MaxPermSize=128m -Xmx$maxmem -XX:OnOutOfMemoryError='kill -9 %p' -DstartupMode=run -Djava.net.preferIPv4Stack=true $JAVAOPTS -jar $jarfile $JAVAARGS
